version: '3'
services:
  db_product:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: product_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
    volumes:
      - product:/var/lib/mysql
    ports:
      - "3306:3306"

  db_auth:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: auth_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
    volumes:
      - auth:/var/lib/mysql
    ports:
      - "3307:3306"

  db_order:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: order_db
      MYSQL_USER: root1234
      MYSQL_PASSWORD: root1234
    volumes:
      - order:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  product:
    driver: local
  auth:
    driver: local
  order:
    driver: local